name: Audit

on:
  pull_request:
    branches:
<<<<<<< HEAD
      - next
=======
      - master
>>>>>>> 5f867c16a7ee6a145ce1c8f348ae9a8896c9faab
  # schedule:
  #   - cron: '0 10 * * *'

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js LTS
      uses: actions/setup-node@v2
      with:
        node-version: lts/*

    - name: Check Vulnerabilities
      run: npm audit --production --audit-level=moderate